name: CI

on:
  push:
    branches: [ main, patch/robust-indicators ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install system deps (optional for TA-Lib)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      - name: Run tests
        run: |
          pytest -q
